# Site settings
title: WTWJBG
email: woojuno@sina.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://woojuno.github.io" # the base hostname & protocol for your site
twitter_username: woojuno
github_username:  woojuno

# Build settings
markdown: kramdown
